CC=gcc
SRCPATH=src/
LDFLAGS= -lpthread -pthread -D_REENTRANT -lrt -Wall

GERADOREXECUTABLE=gerador.out
SAUNAEXECUTABLE=sauna.out

EXECUTABLES= $(GERADOREXECUTABLE) $(SAUNAEXECUTABLE)

all: $(EXECUTABLES)

## GERADOR
GERADORSOURCES= $(SRCPATH)gerador.c

$(GERADOREXECUTABLE): $(GERADORSOURCES)
	$(CC) $(LDFLAGS) $(GERADORSOURCES) -o $(GERADOREXECUTABLE)

## SAUNA
SAUNASOURCES=$(SRCPATH)sauna.c

$(SAUNAEXECUTABLE): $(SAUNASOURCES)
	$(CC) $(LDFLAGS) $(SAUNASOURCES) -o $(SAUNAEXECUTABLE)


clean:
	rm -f *.o $(EXECUTABLES)
