CC=gcc
CFLAGS=-c -Wall
SRCPATH=src/

GERADOREXECUTABLE=gerador.out
SAUNAEXECUTABLE=sauna.out

EXECUTABLES= $(GERADOREXECUTABLE) $(SAUNAEXECUTABLE)

all: $(EXECUTABLES)

## GERADOR
GERADORSOURCES= $(SRCPATH)gerador.c

$(GERADOREXECUTABLE): $(GERADORSOURCES)
	$(CC) $(GERADORSOURCES) -o $(GERADOREXECUTABLE) -Wall

## SAUNA
SAUNASOURCES=$(SRCPATH)sauna.c

$(SAUNAEXECUTABLE): $(SAUNASOURCES)
	$(CC) $(SAUNASOURCES) -o $(SAUNAEXECUTABLE) -Wall


clean:
	rm -f *.o $(EXECUTABLES)
